version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      - MONGODB_URI=mongodb://localhost:27017/seller_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
